"""add timing columns to runs

Revision ID: 2407c574578e
Revises: 80a5ace788b6
Create Date: 2026-03-03 08:19:41.210016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2407c574578e'
down_revision: Union[str, Sequence[str], None] = '80a5ace788b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thinking_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cli_started_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_column('cli_started_at')
        batch_op.drop_column('thinking_started_at')

    # ### end Alembic commands ###
