"""add_fk_agent_message_run_id

Revision ID: 80a5ace788b6
Revises: a1b2c3d4e5f6
Create Date: 2026-03-02 13:44:27.095268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a5ace788b6'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.alter_column('run_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_agent_messages_run_id', 'runs', ['run_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agent_messages_run_id', type_='foreignkey')
        batch_op.alter_column('run_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
