"""initial_tables

Revision ID: bdf9c29f78a5
Revises: 
Create Date: 2026-02-28 20:10:17.221606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf9c29f78a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('sender', sa.Text(), nullable=False),
    sa.Column('role_preset', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_messages_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_session_id'), ['session_id'], unique=False)

    op.create_table('user_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_messages_session_id'), ['session_id'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_message_id', sa.String(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('agent_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_message_id'], ['user_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_session_id'))

    op.drop_table('runs')
    with op.batch_alter_table('user_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_messages_session_id'))

    op.drop_table('user_messages')
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_agent_messages_run_id'))

    op.drop_table('agent_messages')
    op.drop_table('sessions')
    # ### end Alembic commands ###
