"""add llm_provider and llm_model

Revision ID: f27a2374a8c2
Revises: 2407c574578e
Create Date: 2026-03-03 15:54:36.851168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27a2374a8c2'
down_revision: Union[str, Sequence[str], None] = '2407c574578e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_provider', sa.Text(), server_default='claude-cli', nullable=False))
        batch_op.add_column(sa.Column('llm_model', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('llm_model')
        batch_op.drop_column('llm_provider')

    # ### end Alembic commands ###
